### PR TITLE
Meteor's stylus package is deprecated

### PR DESCRIPTION
**Pull request by rootedsoftware**
Update to @hwillson's recommended version
see https://github.com/meteor/meteor/pull/9445

### CODE REVIEW

**Comment by mizzao** [comment]
I am not actively using this project at the moment, so I gave you commit access to make any changes you'd like. If you'd like to directly publish new versions of the package, just send me your Meteor username and I'll add you as a maintainer.

**Comment by c316** [comment]
My Meteor username is joshjoe

So since I can't merge this pull request into master (unless I have write access) would you prefer I just make the change to master then? 

Thanks

**Comment by mizzao** [comment]
```
$ meteor admin maintainers mizzao:tutorials --add joshjoe
Adding a maintainer to mizzao:tutorials...    
                                              
The maintainers for mizzao:tutorials are:     
mizzao                                        
joshjoe                
```

I usually use the following simple procedure for publishing, although you can do what works for you:

- [ ]  Pick an appropriate incremented version number v0.x.y (e.g. 0.4.0 becomes 0.4.1 or 0.5.0 depending on how much changed)
- [ ]  Update the `History.md` file to reflect all changes that will be in the new version. If you've been keeping it up to date, this just involves inserting the above version number below vNEXT.
- [ ]  Update this version number in `package.js`.
- [ ]  git commit (but don't push yet).
- [ ]  Try `meteor publish`
- [ ]  If everything worked, `git tag v0.x.y` and push the tag (`git push origin v0.x.y`; this allows others to find the code for this version) and merge into master and push that too. (If you aren't rebasing the feature branch you may want to merge first before publishing)
- [ ] If publishing didn't work, you can fix things, amend the commit as necessary, then tag and push after verifying that it went through.

Thanks so much for your help!

**Comment by rootedsoftware** [comment]
Thanks for this list, it was helpful.  I've done all of this and pushed 0.6.8 with the stylus fix.

**Pull request merged**
